//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingMeasure.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReceiptReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShippingMeasure.Reports.ReceiptReport", typeof(ReceiptReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aft draft:.
        /// </summary>
        internal static string txtAftDraft {
            get {
                return ResourceManager.GetString("txtAftDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured.
        /// </summary>
        internal static string txtColDensityMeasured_P0 {
            get {
                return ResourceManager.GetString("txtColDensityMeasured_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to density.
        /// </summary>
        internal static string txtColDensityMeasured_P1 {
            get {
                return ResourceManager.GetString("txtColDensityMeasured_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string txtColDensityOfStandard_P0 {
            get {
                return ResourceManager.GetString("txtColDensityOfStandard_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to density.
        /// </summary>
        internal static string txtColDensityOfStandard_P1 {
            get {
                return ResourceManager.GetString("txtColDensityOfStandard_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string txtColHeight {
            get {
                return ResourceManager.GetString("txtColHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string txtColHeightOfWater_P0 {
            get {
                return ResourceManager.GetString("txtColHeightOfWater_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        internal static string txtColHeightOfWater_P1 {
            get {
                return ResourceManager.GetString("txtColHeightOfWater_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string txtColMass_P0 {
            get {
                return ResourceManager.GetString("txtColMass_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtColMass_P1 {
            get {
                return ResourceManager.GetString("txtColMass_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank name.
        /// </summary>
        internal static string txtColTankName {
            get {
                return ResourceManager.GetString("txtColTankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured.
        /// </summary>
        internal static string txtColTemperatureMeasured_P0 {
            get {
                return ResourceManager.GetString("txtColTemperatureMeasured_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature.
        /// </summary>
        internal static string txtColTemperatureMeasured_P1 {
            get {
                return ResourceManager.GetString("txtColTemperatureMeasured_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        internal static string txtColTemperatureOfTank_P0 {
            get {
                return ResourceManager.GetString("txtColTemperatureOfTank_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature.
        /// </summary>
        internal static string txtColTemperatureOfTank_P1 {
            get {
                return ResourceManager.GetString("txtColTemperatureOfTank_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCF20.
        /// </summary>
        internal static string txtColVcf20 {
            get {
                return ResourceManager.GetString("txtColVcf20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string txtColVolume_P0 {
            get {
                return ResourceManager.GetString("txtColVolume_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtColVolume_P1 {
            get {
                return ResourceManager.GetString("txtColVolume_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string txtColVolumeOfStandard_P0 {
            get {
                return ResourceManager.GetString("txtColVolumeOfStandard_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        internal static string txtColVolumeOfStandard_P1 {
            get {
                return ResourceManager.GetString("txtColVolumeOfStandard_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string txtColVolumeOfWater_P0 {
            get {
                return ResourceManager.GetString("txtColVolumeOfWater_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volume.
        /// </summary>
        internal static string txtColVolumeOfWater_P1 {
            get {
                return ResourceManager.GetString("txtColVolumeOfWater_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore draft:.
        /// </summary>
        internal static string txtForeDraft {
            get {
                return ResourceManager.GetString("txtForeDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind:.
        /// </summary>
        internal static string txtKindOfGoods {
            get {
                return ResourceManager.GetString("txtKindOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.:.
        /// </summary>
        internal static string txtNo {
            get {
                return ResourceManager.GetString("txtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port of Destination:.
        /// </summary>
        internal static string txtPortOfDestination {
            get {
                return ResourceManager.GetString("txtPortOfDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port of Shipment:.
        /// </summary>
        internal static string txtPortOfShipment {
            get {
                return ResourceManager.GetString("txtPortOfShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim:.
        /// </summary>
        internal static string txtTrim {
            get {
                return ResourceManager.GetString("txtTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel:.
        /// </summary>
        internal static string txtVesselName {
            get {
                return ResourceManager.GetString("txtVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string txtVesselStatus {
            get {
                return ResourceManager.GetString("txtVesselStatus", resourceCulture);
            }
        }
    }
}
