//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShippingMeasure.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShippingMeasure.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical product.
        /// </summary>
        public static string BuiltInKindChemicalProduct {
            get {
                return ResourceManager.GetString("BuiltInKindChemicalProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crude oil.
        /// </summary>
        public static string BuiltInKindCrudeOil {
            get {
                return ResourceManager.GetString("BuiltInKindCrudeOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Custom].
        /// </summary>
        public static string BuiltInKindCustomized {
            get {
                return ResourceManager.GetString("BuiltInKindCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Add new].
        /// </summary>
        public static string BuiltInKindCustomizedAdd {
            get {
                return ResourceManager.GetString("BuiltInKindCustomizedAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string BuiltInKindDiesel {
            get {
                return ResourceManager.GetString("BuiltInKindDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lubricant.
        /// </summary>
        public static string BuiltInKindLubricant {
            get {
                return ResourceManager.GetString("BuiltInKindLubricant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string BuiltInKindPetrol {
            get {
                return ResourceManager.GetString("BuiltInKindPetrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Petroleum products].
        /// </summary>
        public static string BuiltInKindPetroleumProducts {
            get {
                return ResourceManager.GetString("BuiltInKindPetroleumProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery receipt (destination).
        /// </summary>
        public static string FormTitleDeliveryReceiptDestination {
            get {
                return ResourceManager.GetString("FormTitleDeliveryReceiptDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery receipt (loading).
        /// </summary>
        public static string FormTitleDeliveryReceiptLoading {
            get {
                return ResourceManager.GetString("FormTitleDeliveryReceiptLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string FormTitleLoad {
            get {
                return ResourceManager.GetString("FormTitleLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass of oil.
        /// </summary>
        public static string FormTitleMassOfOil {
            get {
                return ResourceManager.GetString("FormTitleMassOfOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FormTitleSave {
            get {
                return ResourceManager.GetString("FormTitleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density measured
        ///(kg/m³).
        /// </summary>
        public static string HeaderDensityMeasured {
            get {
                return ResourceManager.GetString("HeaderDensityMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard density
        ///(kg/m³).
        /// </summary>
        public static string HeaderDensityOfStandard {
            get {
                return ResourceManager.GetString("HeaderDensityOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height
        ///(m).
        /// </summary>
        public static string HeaderHeight {
            get {
                return ResourceManager.GetString("HeaderHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water height
        ///(m).
        /// </summary>
        public static string HeaderHeightOfWater {
            get {
                return ResourceManager.GetString("HeaderHeightOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass
        ///(t).
        /// </summary>
        public static string HeaderMass {
            get {
                return ResourceManager.GetString("HeaderMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank name.
        /// </summary>
        public static string HeaderTankName {
            get {
                return ResourceManager.GetString("HeaderTankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. measured
        ///(°C).
        /// </summary>
        public static string HeaderTemperatureMeasured {
            get {
                return ResourceManager.GetString("HeaderTemperatureMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank temp.
        ///(°C).
        /// </summary>
        public static string HeaderTemperatureOfTank {
            get {
                return ResourceManager.GetString("HeaderTemperatureOfTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ullage
        ///(m).
        /// </summary>
        public static string HeaderUllage {
            get {
                return ResourceManager.GetString("HeaderUllage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCF20.
        /// </summary>
        public static string HeaderVcf20 {
            get {
                return ResourceManager.GetString("HeaderVcf20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume
        ///(m³).
        /// </summary>
        public static string HeaderVolume {
            get {
                return ResourceManager.GetString("HeaderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard vol.
        ///(m³).
        /// </summary>
        public static string HeaderVolumeOfStandard {
            get {
                return ResourceManager.GetString("HeaderVolumeOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water vol.
        ///(m³).
        /// </summary>
        public static string HeaderVolumeOfWater {
            get {
                return ResourceManager.GetString("HeaderVolumeOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/discharge.
        /// </summary>
        public static string LabelReceiptFor {
            get {
                return ResourceManager.GetString("LabelReceiptFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt date.
        /// </summary>
        public static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total mass (t).
        /// </summary>
        public static string LabelTotalOfMass {
            get {
                return ResourceManager.GetString("LabelTotalOfMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total vol. (m³).
        /// </summary>
        public static string LabelTotalOfVolume {
            get {
                return ResourceManager.GetString("LabelTotalOfVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total standard vol. (m³).
        /// </summary>
        public static string LabelTotalOfVolumeOfStandard {
            get {
                return ResourceManager.GetString("LabelTotalOfVolumeOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total water vol. (m³).
        /// </summary>
        public static string LabelTotaVlOfolumeOfWater {
            get {
                return ResourceManager.GetString("LabelTotaVlOfolumeOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume by Height
        ///.
        /// </summary>
        public static string MenuVolumeByHeight {
            get {
                return ResourceManager.GetString("MenuVolumeByHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume by Ullage.
        /// </summary>
        public static string MenuVolumeByUllage {
            get {
                return ResourceManager.GetString("MenuVolumeByUllage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation finished with error: {0}.
        /// </summary>
        public static string MsgCalcErrorFinish {
            get {
                return ResourceManager.GetString("MsgCalcErrorFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation finished.
        /// </summary>
        public static string MsgCalcFinish {
            get {
                return ResourceManager.GetString("MsgCalcFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating standard density for tank {0}.
        /// </summary>
        public static string MsgCalcInfoDensityOfStandard {
            get {
                return ResourceManager.GetString("MsgCalcInfoDensityOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating mass for tank {0}.
        /// </summary>
        public static string MsgCalcInfoMass {
            get {
                return ResourceManager.GetString("MsgCalcInfoMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating total mass.
        /// </summary>
        public static string MsgCalcInfoTotalOfMass {
            get {
                return ResourceManager.GetString("MsgCalcInfoTotalOfMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating total volume.
        /// </summary>
        public static string MsgCalcInfoTotalOfVolume {
            get {
                return ResourceManager.GetString("MsgCalcInfoTotalOfVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating total standard volume.
        /// </summary>
        public static string MsgCalcInfoTotalOfVolumeOfStandard {
            get {
                return ResourceManager.GetString("MsgCalcInfoTotalOfVolumeOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating total water volume.
        /// </summary>
        public static string MsgCalcInfoTotalOfVolumeOfWater {
            get {
                return ResourceManager.GetString("MsgCalcInfoTotalOfVolumeOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating VCF for tank {0}.
        /// </summary>
        public static string MsgCalcInfoVcf {
            get {
                return ResourceManager.GetString("MsgCalcInfoVcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating volume for tank {0}.
        /// </summary>
        public static string MsgCalcInfoVolume {
            get {
                return ResourceManager.GetString("MsgCalcInfoVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating standard volume for tank {0}.
        /// </summary>
        public static string MsgCalcInfoVolumeOfStandard {
            get {
                return ResourceManager.GetString("MsgCalcInfoVolumeOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating water volume for tank {0}.
        /// </summary>
        public static string MsgCalcInfoVolumeOfWater {
            get {
                return ResourceManager.GetString("MsgCalcInfoVolumeOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density measured is required.
        /// </summary>
        public static string MsgCellErrorDensityMeasured {
            get {
                return ResourceManager.GetString("MsgCellErrorDensityMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard density is required.
        /// </summary>
        public static string MsgCellErrorDensityOfStandard {
            get {
                return ResourceManager.GetString("MsgCellErrorDensityOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height is required.
        /// </summary>
        public static string MsgCellErrorHeight {
            get {
                return ResourceManager.GetString("MsgCellErrorHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water height is required.
        /// </summary>
        public static string MsgCellErrorHeightOfWater {
            get {
                return ResourceManager.GetString("MsgCellErrorHeightOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass is required.
        /// </summary>
        public static string MsgCellErrorMass {
            get {
                return ResourceManager.GetString("MsgCellErrorMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature measured is required.
        /// </summary>
        public static string MsgCellErrorTemperatureMeasured {
            get {
                return ResourceManager.GetString("MsgCellErrorTemperatureMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank temperature is required.
        /// </summary>
        public static string MsgCellErrorTemperatureOfTank {
            get {
                return ResourceManager.GetString("MsgCellErrorTemperatureOfTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass is required.
        /// </summary>
        public static string MsgCellErrorTotalOfMass {
            get {
                return ResourceManager.GetString("MsgCellErrorTotalOfMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume is required.
        /// </summary>
        public static string MsgCellErrorTotalOfVolume {
            get {
                return ResourceManager.GetString("MsgCellErrorTotalOfVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard volume is required.
        /// </summary>
        public static string MsgCellErrorTotalOfVolumeOfStandard {
            get {
                return ResourceManager.GetString("MsgCellErrorTotalOfVolumeOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water volume is required.
        /// </summary>
        public static string MsgCellErrorTotalOfVolumeOfWater {
            get {
                return ResourceManager.GetString("MsgCellErrorTotalOfVolumeOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCF20 is required.
        /// </summary>
        public static string MsgCellErrorVcf {
            get {
                return ResourceManager.GetString("MsgCellErrorVcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume is required.
        /// </summary>
        public static string MsgCellErrorVolume {
            get {
                return ResourceManager.GetString("MsgCellErrorVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard volume is required.
        /// </summary>
        public static string MsgCellErrorVolumeOfStandard {
            get {
                return ResourceManager.GetString("MsgCellErrorVolumeOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water volume is required.
        /// </summary>
        public static string MsgCellErrorVolumeOfWater {
            get {
                return ResourceManager.GetString("MsgCellErrorVolumeOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string MsgConfirmation {
            get {
                return ResourceManager.GetString("MsgConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have not been saved.
        ///
        ///Click OK to confirm that you are sure want to load a receipt.
        ///Otherwise, click Cancel..
        /// </summary>
        public static string MsgConfirmationDiscardToLoad {
            get {
                return ResourceManager.GetString("MsgConfirmationDiscardToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have not been saved.
        ///
        ///Click OK to confirm that you are sure want to create a new receipt.
        ///Otherwise, click Cancel..
        /// </summary>
        public static string MsgConfirmationDiscardToNew {
            get {
                return ResourceManager.GetString("MsgConfirmationDiscardToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while changing password
        ///
        ///{0}.
        /// </summary>
        public static string MsgErrorChangePasswordFailed {
            get {
                return ResourceManager.GetString("MsgErrorChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application encountered configuration issue. Please call 86-21-64035681 to solve the issue. E-MAIL: metrol@sdari.com.cn.
        /// </summary>
        public static string MsgErrorConfigIssue {
            get {
                return ResourceManager.GetString("MsgErrorConfigIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while verifying user login
        ///
        ///{0}.
        /// </summary>
        public static string MsgErrorFailToVerifyUserLogin {
            get {
                return ResourceManager.GetString("MsgErrorFailToVerifyUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user/password.
        /// </summary>
        public static string MsgErrorIncorrectUserAndPassword {
            get {
                return ResourceManager.GetString("MsgErrorIncorrectUserAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string MsgErrorInvalidPassword {
            get {
                return ResourceManager.GetString("MsgErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password not match, login failed.
        /// </summary>
        public static string MsgErrorOldPasswordNotMatch {
            get {
                return ResourceManager.GetString("MsgErrorOldPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password need to be same as New password.
        /// </summary>
        public static string MsgErrorPasswordNotSame {
            get {
                return ResourceManager.GetString("MsgErrorPasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print failed
        ///
        ///{0}.
        /// </summary>
        public static string MsgErrorPrintFailedWithError {
            get {
                return ResourceManager.GetString("MsgErrorPrintFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receipt number &quot;{0}&quot; to be saved, has been used by another receipt.
        ///The existing receipt is {1}.
        ///
        ///Please use another number instead..
        /// </summary>
        public static string MsgErrorReceiptNoUsedByOtherReceiptType {
            get {
                return ResourceManager.GetString("MsgErrorReceiptNoUsedByOtherReceiptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed
        ///
        ///{0}.
        /// </summary>
        public static string MsgErrorSaveFailedWithError {
            get {
                return ResourceManager.GetString("MsgErrorSaveFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to load.
        /// </summary>
        public static string MsgErrorSelectReceiptToLoad {
            get {
                return ResourceManager.GetString("MsgErrorSelectReceiptToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software has been expired. For more information, please call 86-21-64035681. E-MAIL: metrol@sdari.com.cn.
        /// </summary>
        public static string MsgErrorSoftwareExpired {
            get {
                return ResourceManager.GetString("MsgErrorSoftwareExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error
        ///
        ///{0}
        ///
        ///Save anyway? (OK to save).
        /// </summary>
        public static string MsgErrorValidationFailedToSave {
            get {
                return ResourceManager.GetString("MsgErrorValidationFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed, please exit &amp; restart app to take affect.
        /// </summary>
        public static string MsgLanguageChangedPleaseRestart {
            get {
                return ResourceManager.GetString("MsgLanguageChangedPleaseRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove failed.
        /// </summary>
        public static string MsgRemoveKindOfGoodsFailed {
            get {
                return ResourceManager.GetString("MsgRemoveKindOfGoodsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string MsgSaveKindOfGoodsFailed {
            get {
                return ResourceManager.GetString("MsgSaveKindOfGoodsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt changed, not saved.
        /// </summary>
        public static string MsgStatusChangedAndNotSaved {
            get {
                return ResourceManager.GetString("MsgStatusChangedAndNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not saved.
        /// </summary>
        public static string MsgStatusNotSave {
            get {
                return ResourceManager.GetString("MsgStatusNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt loaded.
        /// </summary>
        public static string MsgStatusReceiptLoaded {
            get {
                return ResourceManager.GetString("MsgStatusReceiptLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string MsgStatusSaveFailed {
            get {
                return ResourceManager.GetString("MsgStatusSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save succeeded.
        /// </summary>
        public static string MsgStatusSaveSucceeded {
            get {
                return ResourceManager.GetString("MsgStatusSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aft draft is required.
        /// </summary>
        public static string MsgValidationErrorAftDraft {
            get {
                return ResourceManager.GetString("MsgValidationErrorAftDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Cannot be empty.
        /// </summary>
        public static string MsgValidationErrorCannotBeEmpty {
            get {
                return ResourceManager.GetString("MsgValidationErrorCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Density measured.
        /// </summary>
        public static string MsgValidationErrorDensityMeasured {
            get {
                return ResourceManager.GetString("MsgValidationErrorDensityMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Standard density.
        /// </summary>
        public static string MsgValidationErrorDensityOfStandard {
            get {
                return ResourceManager.GetString("MsgValidationErrorDensityOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore draft is requried.
        /// </summary>
        public static string MsgValidationErrorForeDraft {
            get {
                return ResourceManager.GetString("MsgValidationErrorForeDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Height.
        /// </summary>
        public static string MsgValidationErrorHeight {
            get {
                return ResourceManager.GetString("MsgValidationErrorHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Height of water.
        /// </summary>
        public static string MsgValidationErrorHeightOfWater {
            get {
                return ResourceManager.GetString("MsgValidationErrorHeightOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Invalid status value.
        /// </summary>
        public static string MsgValidationErrorInvalidVesselStatus {
            get {
                return ResourceManager.GetString("MsgValidationErrorInvalidVesselStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind of goods is required.
        /// </summary>
        public static string MsgValidationErrorKindOfGoods {
            get {
                return ResourceManager.GetString("MsgValidationErrorKindOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to Port/Starboard is requried.
        /// </summary>
        public static string MsgValidationErrorListToPortStarboard {
            get {
                return ResourceManager.GetString("MsgValidationErrorListToPortStarboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Discharge is required.
        /// </summary>
        public static string MsgValidationErrorLoadDischarge {
            get {
                return ResourceManager.GetString("MsgValidationErrorLoadDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Mass.
        /// </summary>
        public static string MsgValidationErrorMass {
            get {
                return ResourceManager.GetString("MsgValidationErrorMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port of Destination is required.
        /// </summary>
        public static string MsgValidationErrorPortOfDestination {
            get {
                return ResourceManager.GetString("MsgValidationErrorPortOfDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port of Shipment is required.
        /// </summary>
        public static string MsgValidationErrorPortOfShipment {
            get {
                return ResourceManager.GetString("MsgValidationErrorPortOfShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt number is required.
        /// </summary>
        public static string MsgValidationErrorReceiptNo {
            get {
                return ResourceManager.GetString("MsgValidationErrorReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Temperature meassured.
        /// </summary>
        public static string MsgValidationErrorTemperatureMeasured {
            get {
                return ResourceManager.GetString("MsgValidationErrorTemperatureMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Tank temperature.
        /// </summary>
        public static string MsgValidationErrorTemperatureOfTank {
            get {
                return ResourceManager.GetString("MsgValidationErrorTemperatureOfTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim value is requried.
        /// </summary>
        public static string MsgValidationErrorTrim {
            get {
                return ResourceManager.GetString("MsgValidationErrorTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - VCF.
        /// </summary>
        public static string MsgValidationErrorVcf20 {
            get {
                return ResourceManager.GetString("MsgValidationErrorVcf20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel name is required.
        /// </summary>
        public static string MsgValidationErrorVesselName {
            get {
                return ResourceManager.GetString("MsgValidationErrorVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel status value is required.
        /// </summary>
        public static string MsgValidationErrorVesselStatus {
            get {
                return ResourceManager.GetString("MsgValidationErrorVesselStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Volume.
        /// </summary>
        public static string MsgValidationErrorVolume {
            get {
                return ResourceManager.GetString("MsgValidationErrorVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Standard volume.
        /// </summary>
        public static string MsgValidationErrorVolumeOfStandard {
            get {
                return ResourceManager.GetString("MsgValidationErrorVolumeOfStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Water volume.
        /// </summary>
        public static string MsgValidationErrorVolumeOfWater {
            get {
                return ResourceManager.GetString("MsgValidationErrorVolumeOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgWarn {
            get {
                return ResourceManager.GetString("MsgWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receipt number &quot;{0}&quot; to be saved, is existing in database,
        ///continue to save will overwrite the existing one.
        ///
        ///Click &quot;OK&quot; to overwrite, otherwise click &quot;Cancel&quot;..
        /// </summary>
        public static string MsgWarnExistingReceipt {
            get {
                return ResourceManager.GetString("MsgWarnExistingReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software will be expired on {0}, please contact the software provider ASAP. Business phone: 86-21-64035681. E-MAIL: metrol@sdari.com.cn.
        /// </summary>
        public static string MsgWarnSoftwareExpiration {
            get {
                return ResourceManager.GetString("MsgWarnSoftwareExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery receipt (destination).
        /// </summary>
        public static string ReceiptTypeNameDeliveryReceiptDestination {
            get {
                return ResourceManager.GetString("ReceiptTypeNameDeliveryReceiptDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery receipt (loading).
        /// </summary>
        public static string ReceiptTypeNameDeliveryReceiptLoading {
            get {
                return ResourceManager.GetString("ReceiptTypeNameDeliveryReceiptLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass of oil receipt.
        /// </summary>
        public static string ReceiptTypeNameMassOfOil {
            get {
                return ResourceManager.GetString("ReceiptTypeNameMassOfOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to port.
        /// </summary>
        public static string ReportLabelListToPort {
            get {
                return ResourceManager.GetString("ReportLabelListToPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to starboard.
        /// </summary>
        public static string ReportLabelListToStarboard {
            get {
                return ResourceManager.GetString("ReportLabelListToStarboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●Discharge.
        /// </summary>
        public static string ReportLabelReceiptForDischarge {
            get {
                return ResourceManager.GetString("ReportLabelReceiptForDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●Load.
        /// </summary>
        public static string ReportLabelReceiptForLoad {
            get {
                return ResourceManager.GetString("ReportLabelReceiptForLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string ReportLabelUnitDegree {
            get {
                return ResourceManager.GetString("ReportLabelUnitDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string ReportLabelUnitMetre {
            get {
                return ResourceManager.GetString("ReportLabelUnitMetre", resourceCulture);
            }
        }
    }
}
